# Generated by Django 4.2.6 on 2023-10-19 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakebxapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake_variant',
            name='Catagory',
        ),
        migrations.RemoveField(
            model_name='catagory',
            name='image',
        ),
        migrations.RemoveField(
            model_name='catagory',
            name='name',
        ),
        migrations.AddField(
            model_name='catagory',
            name='types',
            field=models.CharField(choices=[('plum-cake', 'plum-cake'), ('fresh_cream', 'fresh_cream'), ('marble-cake', 'marble-cake'), ('cup-cake', 'cup-cake'), ('cream-cake', 'cream-cake')], default='cream-cake', max_length=200),
        ),
        migrations.CreateModel(
            name='Cakes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('carrot-cake', 'carrot-cake'), ('Red_velvet-cake', 'Red_velvet-cake'), ('cheese-cake', 'cheese-cake'), ('fruit-cake', 'fruit-cake'), ('chiffon-cake', 'chiffon-cake'), ('pound-cake', 'pound-cake'), ('chocolate-cake', 'chocolate-cake'), ('vanila-cake', 'vanila-cake'), ('mango-cake', 'mango-cake'), ('strawberry-cake', 'strawberry-cake'), ('butter-scotch', 'butter-scotch')], max_length=200)),
                ('image', models.ImageField(upload_to='image')),
                ('Catagory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cakebxapp.catagory')),
            ],
        ),
        migrations.AddField(
            model_name='cake_variant',
            name='Cake',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cakebxapp.cakes'),
        ),
    ]
