# Generated by Django 4.2.6 on 2023-10-25 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakebxapp', '0002_remove_cake_variant_catagory_remove_catagory_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake_variant',
            name='Cake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakebxapp.cakes'),
        ),
    ]
