# Generated by Django 4.2.6 on 2023-10-25 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakebxapp', '0003_alter_cake_variant_cake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cakes',
            name='Catagory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakebxapp.catagory'),
        ),
    ]
