# Generated by Django 4.2.6 on 2023-11-27 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakebxapp', '0004_alter_cakes_catagory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='Cake_variant',
        ),
        migrations.AddField(
            model_name='reviews',
            name='cake',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cakebxapp.cakes'),
        ),
    ]
